version: '3.7'

services:
  nginx:
    image: jwilder/nginx-proxy:0.9-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/conf.d:/etc/nginx/conf.d

  backend:
    image: nachoyegro/seguimiento-academico-backend:v1.2.3
    ports:
      - "8000:8001"
    depends_on:
      - memcached
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=admin-seguimiento.unq.edu.ar
      - VIRTUAL_PORT=8001

  analisis:
    image: nachoyegro/seguimiento-academico-analisis:v1.2
    ports:
      - "5000:5000"
    volumes:
      - ./analisis/data:/code/data
    depends_on:
      - memcached
      - backend
    environment:
      - VIRTUAL_HOST=analisis-seguimiento.unq.edu.ar
      - VIRTUAL_PORT=5000

  front:
    image: nachoyegro/seguimiento-academico-front:v1.2
    ports:
      - "3000:3000"
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=visual-seguimiento.unq.edu.ar
      - VIRTUAL_PORT=3000

  memcached:
    image: memcached:1.6.9
    ports:
      - 11211:11211
